### ISSUE TITLE
[BUG]  o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_6/

### ISSUE THREAD

**Issue by ghost** [emalderson/ThePhish#14]
**Describe the bug**

**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu Server  |
| OS version (client)        | 20.04           |
| Python version | |
| Type of email address used | Gmail, Hotmail, ... |
| Mail client type & version | Thunderbird, Gmail, ... |
| Browser type & version     | Firefox, Chrome, Edge, Opera, ...                    |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 4   |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True / False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**To Reproduce**

Run docker-compose up

and get:

![image](https://user-images.githubusercontent.com/62509895/162508739-22e22aba-6ea1-4b1a-8eb5-a2e03e197d02.png)

I already tried the steps with:

![image](https://user-images.githubusercontent.com/62509895/162508905-4f21fd85-842c-4026-9e72-b90aa4fc42d8.png)

Thanks for help!

**Comment by emalderson** [comment]
Hi, Guilherme, that error is actually strange, I've never seen it before and I'm not able to replicate it. The part of the documentation that you linked is related to another type of error caused by some permission issue during the folder creation (sorry for not having been precise enough regarding the error that I intended there). 
Anyway, it seems that someone else has already ran into a similar error in this issue on the Cortex GitHub repo, maybe it can help you find a solution: https://github.com/TheHive-Project/Cortex/issues/305

**Comment by emalderson** [comment]
Hello, I managed to reproduce the issue, but it is not a problem if you see that error, just proceed with the guide and everything should work as intended. Just ignore it.
