### ISSUE TITLE
[Question] Handling URL rewrite 

### ISSUE THREAD

**Issue by CipherFrame** [emalderson/ThePhish#27]
My environment passes all email through Cisco Secure Email Security, which will rewrite URLs with a neutral or unknown reputation to redirect them to the Cisco Web Security Proxy for click-time evaluation of their safety.

For those emails which slip through and are reported as suspicious/malicious, I would like to use ThePhish as my analysis and logging platform. 

Does ThePhish have a capability to decode these URL rewrites so that the true URL is analyzed ?

**Comment by emalderson** [comment]
At the moment ThePhish is only able to unshorten links that are shortened using some common URL shorteners, it doesn't support URL rewriting for specific platforms like the one you mentioned. However, if you know what are the steps performed during this transformation, it may be trivial to write a function that reverts the process so that it's called before the URL is analyzed.

**Comment by tordormore** [comment]
AppRiver (formerly ZixCorp) does something similar.  It takes a url and puts it in the format of (https://link.edgepilot.com/s/<randomcharacters>)u=(https://<Original URL>)  NOTE: Parentheses and brackets added by me.  Would love to have a feature added to automatically transform those back to the original URL.
